version: "3.9"
services:
  fileshare:
    build: .
    container_name: fileshare
    restart: unless-stopped
    ports:
      - "3000:3001"
    environment:
      PORT: 3001
      PUBLIC_URL: https://share.vextroboomin.xyz
      ADMIN_PASSWORD: "8762"
    volumes:
      - ./data:/app/data
      - ./uploads:/app/uploads
      - ./EMBED:/app/EMBED
